// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: Header.proto

package hermes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header_Type int32

const (
	Header_Network Header_Type = 0
	Header_File    Header_Type = 1
)

// Enum value maps for Header_Type.
var (
	Header_Type_name = map[int32]string{
		0: "Network",
		1: "File",
	}
	Header_Type_value = map[string]int32{
		"Network": 0,
		"File":    1,
	}
)

func (x Header_Type) Enum() *Header_Type {
	p := new(Header_Type)
	*p = x
	return p
}

func (x Header_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Header_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_Header_proto_enumTypes[0].Descriptor()
}

func (Header_Type) Type() protoreflect.EnumType {
	return &file_Header_proto_enumTypes[0]
}

func (x Header_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Header_Type.Descriptor instead.
func (Header_Type) EnumDescriptor() ([]byte, []int) {
	return file_Header_proto_rawDescGZIP(), []int{1, 0}
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vmajor uint32 `protobuf:"varint,1,opt,name=vmajor,proto3" json:"vmajor,omitempty"` // do not use major it conflict with some macros
	Vminor uint32 `protobuf:"varint,2,opt,name=vminor,proto3" json:"vminor,omitempty"` // do not use minor it conflict with some macros
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_Header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_Header_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetVmajor() uint32 {
	if x != nil {
		return x.Vmajor
	}
	return 0
}

func (x *Version) GetVminor() uint32 {
	if x != nil {
		return x.Vminor
	}
	return 0
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version        *Version    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Type           Header_Type `protobuf:"varint,2,opt,name=type,proto3,enum=fort.hermes.Header_Type" json:"type,omitempty"`
	Previous       string      `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Width          int32       `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32       `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	ExtensionTypes []string    `protobuf:"bytes,6,rep,name=extensionTypes,proto3" json:"extensionTypes,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Header_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_Header_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_Header_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Header) GetType() Header_Type {
	if x != nil {
		return x.Type
	}
	return Header_Network
}

func (x *Header) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *Header) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Header) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Header) GetExtensionTypes() []string {
	if x != nil {
		return x.ExtensionTypes
	}
	return nil
}

type Footer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Next string `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *Footer) Reset() {
	*x = Footer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Header_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Footer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Footer) ProtoMessage() {}

func (x *Footer) ProtoReflect() protoreflect.Message {
	mi := &file_Header_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Footer.ProtoReflect.Descriptor instead.
func (*Footer) Descriptor() ([]byte, []int) {
	return file_Header_proto_rawDescGZIP(), []int{2}
}

func (x *Footer) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

type FileLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Readout *FrameReadout `protobuf:"bytes,1,opt,name=readout,proto3" json:"readout,omitempty"`
	Footer  *Footer       `protobuf:"bytes,2,opt,name=footer,proto3" json:"footer,omitempty"`
}

func (x *FileLine) Reset() {
	*x = FileLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Header_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLine) ProtoMessage() {}

func (x *FileLine) ProtoReflect() protoreflect.Message {
	mi := &file_Header_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLine.ProtoReflect.Descriptor instead.
func (*FileLine) Descriptor() ([]byte, []int) {
	return file_Header_proto_rawDescGZIP(), []int{3}
}

func (x *FileLine) GetReadout() *FrameReadout {
	if x != nil {
		return x.Readout
	}
	return nil
}

func (x *FileLine) GetFooter() *Footer {
	if x != nil {
		return x.Footer
	}
	return nil
}

var File_Header_proto protoreflect.FileDescriptor

var file_Header_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x66, 0x6f, 0x72, 0x74, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x1a, 0x12, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x39, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6d,
	0x61, 0x6a, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6d, 0x61, 0x6a,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x76, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x22, 0xf7, 0x01, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x68, 0x65,
	0x72, 0x6d, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65,
	0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x26, 0x0a,
	0x0e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69,
	0x6c, 0x65, 0x10, 0x01, 0x22, 0x1c, 0x0a, 0x06, 0x46, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65,
	0x78, 0x74, 0x22, 0x6c, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x33,
	0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64,
	0x6f, 0x75, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65,
	0x73, 0x2e, 0x46, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72,
	0x42, 0x28, 0x48, 0x03, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x69, 0x63, 0x69, 0x64, 0x61, 0x65, 0x2d, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_Header_proto_rawDescOnce sync.Once
	file_Header_proto_rawDescData = file_Header_proto_rawDesc
)

func file_Header_proto_rawDescGZIP() []byte {
	file_Header_proto_rawDescOnce.Do(func() {
		file_Header_proto_rawDescData = protoimpl.X.CompressGZIP(file_Header_proto_rawDescData)
	})
	return file_Header_proto_rawDescData
}

var file_Header_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Header_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Header_proto_goTypes = []interface{}{
	(Header_Type)(0),     // 0: fort.hermes.Header.Type
	(*Version)(nil),      // 1: fort.hermes.Version
	(*Header)(nil),       // 2: fort.hermes.Header
	(*Footer)(nil),       // 3: fort.hermes.Footer
	(*FileLine)(nil),     // 4: fort.hermes.FileLine
	(*FrameReadout)(nil), // 5: fort.hermes.FrameReadout
}
var file_Header_proto_depIdxs = []int32{
	1, // 0: fort.hermes.Header.version:type_name -> fort.hermes.Version
	0, // 1: fort.hermes.Header.type:type_name -> fort.hermes.Header.Type
	5, // 2: fort.hermes.FileLine.readout:type_name -> fort.hermes.FrameReadout
	3, // 3: fort.hermes.FileLine.footer:type_name -> fort.hermes.Footer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Header_proto_init() }
func file_Header_proto_init() {
	if File_Header_proto != nil {
		return
	}
	file_FrameReadout_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Header_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Header_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Footer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Header_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Header_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Header_proto_goTypes,
		DependencyIndexes: file_Header_proto_depIdxs,
		EnumInfos:         file_Header_proto_enumTypes,
		MessageInfos:      file_Header_proto_msgTypes,
	}.Build()
	File_Header_proto = out.File
	file_Header_proto_rawDesc = nil
	file_Header_proto_goTypes = nil
	file_Header_proto_depIdxs = nil
}
