// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: Tag.proto

package hermes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    uint32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	X     float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Theta float64 `protobuf:"fixed64,4,opt,name=theta,proto3" json:"theta,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_Tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_Tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Tag) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tag) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Tag) GetTheta() float64 {
	if x != nil {
		return x.Theta
	}
	return 0
}

var File_Tag_proto protoreflect.FileDescriptor

var file_Tag_proto_rawDesc = []byte{
	0x0a, 0x09, 0x54, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x66, 0x6f, 0x72,
	0x74, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x68, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x68, 0x65, 0x74,
	0x61, 0x42, 0x28, 0x48, 0x03, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x69, 0x63, 0x69, 0x64, 0x61, 0x65, 0x2d, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Tag_proto_rawDescOnce sync.Once
	file_Tag_proto_rawDescData = file_Tag_proto_rawDesc
)

func file_Tag_proto_rawDescGZIP() []byte {
	file_Tag_proto_rawDescOnce.Do(func() {
		file_Tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_Tag_proto_rawDescData)
	})
	return file_Tag_proto_rawDescData
}

var file_Tag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Tag_proto_goTypes = []interface{}{
	(*Tag)(nil), // 0: fort.hermes.Tag
}
var file_Tag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Tag_proto_init() }
func file_Tag_proto_init() {
	if File_Tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Tag_proto_goTypes,
		DependencyIndexes: file_Tag_proto_depIdxs,
		MessageInfos:      file_Tag_proto_msgTypes,
	}.Build()
	File_Tag_proto = out.File
	file_Tag_proto_rawDesc = nil
	file_Tag_proto_goTypes = nil
	file_Tag_proto_depIdxs = nil
}
