Document: fort-hermes
Title: Debian fort-hermes Manual
Author: <insert document author here>
Abstract: This manual describes what fort-hermes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fort-hermes/fort-hermes.sgml.gz

Format: postscript
Files: /usr/share/doc/fort-hermes/fort-hermes.ps.gz

Format: text
Files: /usr/share/doc/fort-hermes/fort-hermes.text.gz

Format: HTML
Index: /usr/share/doc/fort-hermes/html/index.html
Files: /usr/share/doc/fort-hermes/html/*.html
